version: "3"
services:
  web:
    build: .
    command: mix phx.server
    environment:
      MIX_ENV: "dev"
      PORT: "4000"
    volumes:
      - ./app:/app
    working_dir: /app
    ports:
      - "4000:4000"
    tty: true
