version: "3"
services:
  db:
    image: postgres:12.1-alpine
    volumes:
      - /opt/db:/var/lib/postgresql/data
  web:
    build: .
    command: bash
    environment:
      - COMPOSE_FILE
    volumes:
      - /work/projects:/projects
    working_dir: /projects
    ports:
      - "4000:4000"
    depends_on:
      - db
    tty: true
