version: "3"
services:
  db:
    image: postgres:12.1-alpine
    volumes:
      - /opt/db:/var/lib/postgresql/data
  web:
    build: .
    command: mix phx.server
    environment:
      MIX_ENV: "dev"
      PORT: "4000"
    volumes:
      - ./app:/app
      - /home/vagrant/_build:/app/_build
      - /home/vagrant/deps:/app/deps
      - /home/vagrant/assets/node_modules:/app/assets/node_modules
    working_dir: /app
    ports:
      - "4000:4000"
    depends_on:
      - db
    tty: true
